
all:
	g++ -o v4l2stereo main.cpp anyoption.cpp drawing.cpp ../libv4l2cam/libcam.cpp stereo.cpp -I/usr/local/include/opencv -L/usr/local/lib -lcv -lcxcore -lcvaux -lhighgui

clean:
	rm -f v4l2stereo




