
all:
	g++ -o test test.cpp -L.. -lcam -I/usr/include/opencv2 -L/usr/lib -lcv -lcxcore -lcvaux -lhighgui
	g++ -o two two.cpp -L.. -lcam -I/usr/include/opencv2 -L/usr/lib -lcv -lcxcore -lcvaux -lhighgui

clean:
	rm -f test
	rm -f two
